import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-background':              '#dde2f8',
        'on-tertiary-fixed-variant':  '#653e00',
        'on-tertiary-container':      '#523200',
        'on-secondary-fixed-variant': '#004395',
        'inverse-surface':            '#dde2f8',
        'inverse-primary':            '#006c49',
        'primary-fixed-dim':          '#4edea3',
        'secondary':                  '#adc6ff',
        'tertiary-fixed-dim':         '#ffb95f',
        'outline-variant':            '#3c4a42',
        'error':                      '#ffb4ab',
        'secondary-fixed-dim':        '#adc6ff',
        'surface-container':          '#191f2f',
        'tertiary-container':         '#e29100',
        'surface-container-high':     '#242a3a',
        'surface-dim':                '#0d1322',
        'on-tertiary-fixed':          '#2a1700',
        'primary':                    '#4edea3',
        'background':                 '#0b1120',
        'surface-variant':            '#2f3445',
        'on-tertiary':                '#472a00',
        'surface-container-lowest':   '#080e1d',
        'primary-fixed':              '#6ffbbe',
        'surface':                    '#0d1322',
        'on-surface-variant':         '#bbcabf',
        'secondary-container':        '#0566d9',
        'on-secondary':               '#002e6a',
        'on-primary-container':       '#00422b',
        'tertiary-fixed':             '#ffddb8',
        'outline':                    '#86948a',
        'error-container':            '#93000a',
        'surface-container-highest':  '#2f3445',
        'surface-container-low':      '#151b2b',
        'surface-tint':               '#4edea3',
        'surface-bright':             '#33394a',
        'on-error-container':         '#ffdad6',
        'on-secondary-fixed':         '#001a42',
        'tertiary':                   '#ffb95f',
        'primary-container':          '#10b981',
        'on-secondary-container':     '#e6ecff',
        'inverse-on-surface':         '#2a3040',
        'on-primary-fixed-variant':   '#005236',
        'on-error':                   '#690005',
        'on-primary':                 '#003824',
        'secondary-fixed':            '#d8e2ff',
        'on-primary-fixed':           '#002113',
        'on-surface':                 '#dde2f8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        'margin-mobile':  '16px',
        'gutter':         '24px',
        'margin-desktop': '80px',
        'base':           '4px',
        'section-padding':'120px',
      },
      fontFamily: {
        'label-sm':           ['Inter', 'sans-serif'],
        'display-lg':         ['Inter', 'sans-serif'],
        'headline-md':        ['Inter', 'sans-serif'],
        'headline-lg':        ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg':            ['Inter', 'sans-serif'],
        'body-md':            ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm':           ['12px',  { lineHeight: '16px', letterSpacing: '0.05em',  fontWeight: '600' }],
        'display-lg':         ['64px',  { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md':        ['24px',  { lineHeight: '32px',                           fontWeight: '600' }],
        'headline-lg':        ['40px',  { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px',  { lineHeight: '40px',                           fontWeight: '700' }],
        'body-lg':            ['18px',  { lineHeight: '28px',                           fontWeight: '400' }],
        'body-md':            ['16px',  { lineHeight: '24px',                           fontWeight: '400' }],
      },
      animation: {
        'float':      'float 6s ease-in-out infinite',
        'float-slow': 'float 8s ease-in-out infinite',
        'float-fast': 'float 4s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':       { transform: 'translateY(-10px)' },
        },
      },
      boxShadow: {
        'glow-primary': '0 0 15px rgba(16, 185, 129, 0.3)',
        'glow-lg':      '0 0 30px rgba(16, 185, 129, 0.15)',
        'float-icon':   '0 4px 20px rgba(0, 0, 0, 0.5)',
      },
    },
  },
  plugins: [],
}

export default config
